export const equipmentOptions = [
  "DJ System",
  "MDJ",
  "Mixers",
  "Speakers",
  "Powered Speakers",
  "Speaker Arrays",
  "Wireless Kits",
  "DIs",
  "Pro Audio",
  "Lectern Mics",
  "Audio - Other",
  "Video Racks",
  "Video Converters",
  "Video Distro",
  "LED Wall",
  "Studio Cameras",
  "Speciality Cameras",
  "Laptops",
  "PPT Remotes",
  "Blu-Ray Players",
  "Projector",
  "Lenses",
  "Screen",
  "Flat Screen",
  "FPD Stands",
  "Video - Other",
  "Lighting Control",
  "LED Uplights",
  "Lekos",
  "Light Kit",
  "Movers",
  "Effects",
  "LED Tree",
  "Lighting",
  "UPS",
  "AC Case",
  "Generator",
  "Power",
  "HD Stands",
  "Rigging",
  "Tents",
  "Staging",
  "Staging/Tents",
  "Communications",
  "Networking",
  "Lecterns",
  "Photography",
  "Drape & Pipe",
  "Vehicle",
  "Trailer",
  "Studio",
  "Decor",
  "Office",
  "Staffing",
];

export const parentItemCodeCategories = [
  "DJ Hours",
  "Mitzvah Packages",
  "School Packages",
  "Activation Packages",
  "Other Packages",
  "Entertainers",
  "Musicians",
  "Photo Booths & IPS",
  "Grace & Gold",
  "Videography",
  "Photography",
  "Photo Add-ons",
  "Studio",
  "Audio Items",
  "Video Items",
  "Lighting Items",
  "Rigging",
  "A/V",
  "Amusements",
  "Stageline",
  "Staging & Dance Floor",
  "Drape",
  "Decor",
  "Floral",
  "Rentals",
  "Power",
  "Party Supplies",
  "Misc",
  "Staffing",
];

export const costingDepartmenCategories = [
  "Technical",
  "DJ",
  "Grace & Gold",
  "Photography",
  "Videography",
  "Broadcast Video",
  "Decor/Design",
  "Flora",
  "Salon",
  "Studio",
  "IPS/Photobooth",
  "Entertainment",
  "Amusements",
  "Musicians",
  "Rental",
  "Subcontracted",
  "Sale",
  "Discount",
  "Other",
];
